### ISSUE TITLE
Doesn't work in Intellij WebStrom

### ISSUE THREAD

**Issue by Asaf-S** [anseki/gulp-confirm#2]
This segment:

gulp.src(srcPathsWithoutVideos)
        .pipe(gulp_confirm({
            question: 'This processing requires about 10 minutes. Continue?',
            input: '_key:y'
        }))

causes the following problem:

stty: /dev/tty: Device not configured
<...>/node_modules/readline-sync/lib/read.sh: line 49: /dev/tty: Device not configured
stty: /dev/tty: Device not configured
<...>/node_modules/readline-sync/lib/readline-sync.js:250
    if (res.error) { throw res.error; }
                     ^

Error: The current environment doesn't support interactive reading from TTY.
stty: /dev/tty: Device not configured
<...>/node_modules/readline-sync/lib/read.sh: line 49: /dev/tty: Device not configured
stty: /dev/tty: Device not configured
    at readlineExt (<...>/node_modules/readline-sync/lib/readline-sync.js:212:19)
    at tryExt (<...>/node_modules/readline-sync/lib/readline-sync.js:249:15)
    at <...>/node_modules/readline-sync/lib/readline-sync.js:352:15
    at _readlineSync (<...>/node_modules/readline-sync/lib/readline-sync.js:422:5)
    at Object.exports.keyIn (<...>/node_modules/readline-sync/lib/readline-sync.js:877:17)
    at Confirm.transform (<...>/node_modules/gulp-confirm/index.js:75:34)
    at DestroyableTransform._transform (<...>/node_modules/gulp-confirm/index.js:33:57)
    at DestroyableTransform.Transform._read (<...>/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (<...>/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (<...>/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (<...>/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (<...>/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at write (<...>/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (<...>/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (<...>/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:86:13)

Process finished with exit code 1

**Comment by anseki** [comment]
Hi @Asaf-S, thank you for the comment.
So, see the error message: "The current environment doesn't support interactive reading from TTY."

Since gulp-confirm has a conversation with the user via TTY, of course it can't work in an environment without TTY, other programs that use TTY too. For example, REPL also may not work. try this:
```
node
console.log('foo');
```
You should use it in an environment that TTY is available.

**Comment by anseki** [comment]
No reply came. I close this issue.
